name: Continuous Deployment - Haste Server

on:
  push:
    branches:
      - main
    paths:
      - 'haste-server/**'
      - '.github/workflows/haste-server-deployment.yml'

jobs:
  HasteServer-Image-GitHub:
    name: Publish haste-server image to Github Package Registry
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Publish to Github Package Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: skyra-project/docker-images/haste-server
          workdir: haste-server
          username: NM-EEA-Y
          password: ${{ secrets.SKYRA_TOKEN }}
          tags: 'latest,stable,master,main'
          registry: docker.pkg.github.com

  HasteServer-Image-Dockerhub:
    name: Publish haste-server image to Dockerhub
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: skyrabot/haste-server
          workdir: haste-server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'latest,stable,master,main'
