name: Continuous Deployment - Lavalink

on:
  push:
    branches:
      - master
    paths:
      - 'lavalink/**'

jobs:
  Lavalink-Image:
    name: Publish lavalink image to Github Package Registry
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Publish to Github Package Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: skyrabot/docker-images/lavalink
          workdir: lavalink
          username: NM-EEA-Y
          password: ${{ secrets.SKYRA_TOKEN }}
          tags: 'latest,stable,master'
          registry: docker.pkg.github.com