name: Continuous Deployment - Lavalink

on:
  push:
    branches:
      - main
    paths:
      - 'lavalink/**'
      - '.github/workflows/lavalink-deployment.yml'

jobs:
  Lavalink-Image-GitHub:
    name: Publish lavalink image to Github Package Registry
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Publish to Github Package Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: skyra-project/docker-images/lavalink
          workdir: lavalink
          username: NM-EEA-Y
          password: ${{ secrets.SKYRA_TOKEN }}
          tags: 'latest,stable,master,main'
          registry: docker.pkg.github.com

  Lavalink-Image-Dockerhub:
    name: Publish lavalink image to Dockerhub
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          name: skyrabot/lavalink
          workdir: lavalink
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'latest,stable,master,main'
