name: Continuous Deployment - Postgres

on:
  push:
    branches:
      - main
    paths:
      - 'postgres/**'
      - '.github/workflows/postgres-deployment.yml'

jobs:
  Postgres-Image-GitHub:
    name: Publish postgres image to Github Package Registry
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Publish to Github Package Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: skyra-project/docker-images/postgres
          workdir: postgres
          username: NM-EEA-Y
          password: ${{ secrets.SKYRA_TOKEN }}
          tags: 'latest,stable,master,main'
          registry: docker.pkg.github.com

  Postgres-Image-Dockerhub:
    name: Publish postgres image to Dockerhub
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: skyrabot/postgres
          workdir: postgres
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'latest,stable,master,main'
